### ISSUE TITLE
APR support

### ISSUE THREAD

**Issue by lduparc** [bitnami/bitnami-docker-tomcat#76]
How to install libtcnative for Apache Portable Runtime (APR) based Native library for Tomcat in order to improve performance ?

**Comment by alemorcuq** [comment]
Hi, @lduparc.

`libtcnative` is available from both the Debian and the Oracle Linux repositories. You can install it in Debian with:

```
install_packages libtcnative-1
```

and in Oracle Linux with:

```
install_packages tomcat-native
```

Is this enough for you?

**Comment by lduparc** [comment]
Well I already try to install `libtcnative-1` but nothing change. When tomcat start I've got the same message like : 

```
The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path
```

and my Dockerfile looks like : 

```
...
RUN install_packages libc6 libgcc1 libtcnative-1 
RUN bitnami-pkg install java-1.8.212-0 --checksum 54a18672c8b4c1a44324c607a6bc616f614a062005d5e3384f91f10ff6f6edea
RUN bitnami-pkg unpack tomcat-8.5.41-0 --checksum 655bd82505694bdcb2f7e4831b5a10f934e125ecc52056f2438721e6d9cf5c8a
...
```

**Comment by lduparc** [comment]
Thanks a lot it's working as expected.

**Comment by alemorcuq** [comment]
Hi, @lduparc.

I'm going to leave this open since this is a feature we would like to support, as the solution provided is just a workaround. I'll come back to you when I have some news to share.

Regards,
Alejandro

**Comment by schnatterer** [comment]
Hey @alemorcuq,

thanks for your workaround, it helped me building APR.

Doing so, I've found out from the [tomcat docs]() that the native lib sources are also contained in `bin/tomcat-native.tar.gz archive`. 
So the whole process can be simplified by using the  `bitnami/tomcat` image for building. 
Combined with a multi stage build this leads to a much smaller image and less cluttered `Dockerfile`.

An example: [schnatterer/smeagol-galore](https://github.com/schnatterer/smeagol-galore/blob/d51bfbfca8dda63a2675cc3f14c66b0106403bf3/Dockerfile#L95).

Maybe this is helpful for others trying to use APR.

**Comment by marcosbc** [comment]
@schnatterer AFAIK we included both APR and Tomcat Native library in the Tomcat container some months ago. You can see that by running the latest 8.5 image and checking the logs:

```
13-Apr-2020 10:50:33.097 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.23] using APR version [1.7.0].
13-Apr-2020 10:50:33.097 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
13-Apr-2020 10:50:33.097 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
13-Apr-2020 10:50:33.099 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
...
13-Apr-2020 10:50:33.097 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.23] using APR version [1.7.0].
```

Could you verify that you're using an updated container image? Any releases in 2020 should already contain it.

**Comment by marcosbc** [comment]
@schnatterer It looks like your problem is happening because you are overwriting "entrypoint.sh".

Keep in mind that this function not only serves as the container entrypoint, but also is responsible for executing the `setup.sh` script for initializing Tomcat. This script is located at `/opt/bitnami/scripts/tomcat`.

In any case, since you are already changing the configuration to your will, you may be able to skip the setup altogether. However, there is one fundamental part that must be kept, and is the creation of the `/opt/bitnami/tomcat/bin/setenv.sh`. It has the following contents:

```bash
#!/bin/bash
JAVA_HOME="/opt/bitnami/java"
export JAVA_HOME

JAVA_OPTS="-Djava.awt.headless=true -XX:+UseG1GC -Dfile.encoding=UTF-8"
export JAVA_OPTS

# Load Tomcat Native library
LD_LIBRARY_PATH="/opt/bitnami/tomcat/lib:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH
```

Once you fill the file with those contents, you should see it works properly.

**Comment by marcosbc** [comment]
It looks like this issue was resolved in the end, so I'm closing this issue.

**Comment by schnatterer** [comment]
@marcosbc 🙈 missed that one when migrating my entrypoint from the tomcat library base image.

Thanks for taking your time to provide a solution, especially if it wasn't the actual issue here.

I came here thinking my reply could be helpful for others, when finally it was me who got a helpful reply. Gotta love OSS 😉👍
