### ISSUE TITLE
Install nginx with tomcat

### ISSUE THREAD

**Issue by lduparc** [bitnami/bitnami-docker-tomcat#77]
How to install nginx with tomcat ?

I found a sample with wordpress + nginx + mysql but I don't know how to start tomcat and nginx. For now tomcat is started using `nami start --foreground tomcat` and we need to start nginx too.

Have a sample with both ?

**Comment by miguelaeh** [comment]
Hi @lduparc ,
you can use the https://github.com/bitnami/bitnami-docker-nginx image to have an nginx image. After that, configure the configurations files and it should work. You can follow this guide to setup the configuration: https://www.mkyong.com/nginx/nginx-apache-tomcat-configuration-example/

**Comment by lduparc** [comment]
Not so easy. bitnami-docker-tomcat and bitnami-docker-nginx are not using the same version of bitnami/minideb-extras. I encounter issues with missing files copying scripts and nginx dockerfile to tomcat existing Dockerfile. Regarding nginx config with tomcat, this is not a problem, I already have a working version with an external nginx. But I would like to have nginx running with tomcat container.

Some errors: 
```
/libnginx.sh: line 8: /libfile.sh: No such file or directory
/libnginx.sh: line 9: /liblog.sh: No such file or directory
/libnginx.sh: line 10: /libos.sh: No such file or directory
/libnginx.sh: line 11: /libservice.sh: No such file or directory
/libnginx.sh: line 12: /libvalidations.sh: No such file or directory
/postunpack.sh: line 7: /libfs.sh: No such file or directory
/postunpack.sh: line 22: ensure_dir_exists: command not found
/postunpack.sh: line 22: ensure_dir_exists: command not found
/postunpack.sh: line 22: ensure_dir_exists: command not found
/postunpack.sh: line 22: ensure_dir_exists: command not found
/postunpack.sh: line 22: ensure_dir_exists: command not found
/postunpack.sh: line 22: ensure_dir_exists: command not found
/postunpack.sh: line 22: ensure_dir_exists: command not found
/libnginx.sh: line 132: debug: command not found
/postunpack.sh: line 38: debug: command not found
mv: cannot overwrite non-directory '/app' with directory '/opt/bitnami/nginx/html'
/postunpack.sh: line 59: warn: command not found
```

**Comment by miguelaeh** [comment]
Hi @lduparc ,
Not sure about what are you trying to do. If I understand you copied the Nginx scripts to tomcat Dockerfile, right?
Why do you want to use both at the same container and not as separate services? I mean, you can deploy one container with tomcat and other with Nginx and connect them.
If you deploy the two services at the same container you have to start one at background, and after the other. If the first died, the container will continue running because the main process would be the second service. So, in case the first died, your container will continue running and you could not notice that actually the service is not running.

**Comment by lduparc** [comment]
You right, I have created a new container with nginx instead of having both under the same container. Everything is working as expected. In this case I'm able to monitor and do updates independently.
