### ISSUE TITLE
Option to enable the HTTP manager interface

### ISSUE THREAD

**Issue by windmueller** [bitnami/bitnami-docker-tomcat#92]
As mentioned in #90, it is currently not possible to use the HTTP manager interface. Unfortunately the PR hs been closed because of inactivity.

I am trying to find a workaround for this issue, but patching the XML file by overwriting "COMMAND" does not work since it is called with exec in double quotes from the entrypoint script.

Either way, it would be nice to have an option enabling the usage of the HTTP manager interface.

**Comment by alemorcuq** [comment]
I can create an internal task to add this feature, but I can't give you an ETA. Would you be interested in creating a PR for this?

**Comment by windmueller** [comment]
Sorry, I do not have the time for fixing this myself. However, I found a workaround by patching the official Tomcat image. I still would prefer the solution using your image though because setting environment variables seems much cleaner to me.

**Comment by alemorcuq** [comment]
Thanks, @windmueller. I will create the task.

**Comment by carrodher** [comment]
Hi, unfortunately, due to we are a small team and other priorities we have, we didn't find the bandwidth to work on this feature. Taking a look at our roadmap there are no plans to work on it in the short/mid term.

If you like to contribute, the Bitnami team will be happy to review any PR and provide feedback. [Here](https://github.com/bitnami/bitnami-docker-tomcat/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
